package latihan_uas.view;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import latihan_uas.DBConnection;
import latihan_uas.entity.Peminjaman;
import latihan_uas.entity.PeminjamanDetail;
import latihan_uas.model.PeminjamanDetailTableModel;
import latihan_uas.model.PeminjamanModel;
import latihan_uas.model.PeminjamanDetailModel;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Vector;
public class PeminjamanForm extends javax.swing.JInternalFrame {

    private Connection connection;
    private PeminjamanDetailTableModel peminjamanDetailTableModel;
    private PeminjamanModel peminjamanModel;
    private PeminjamanDetailModel peminjamanDetailModel;
    public PeminjamanForm() {
        initComponents();
        
        connection = DBConnection.newgetInstant();
        peminjamanDetailTableModel = new PeminjamanDetailTableModel(new ArrayList<PeminjamanDetail>());
        tableRender();
        peminjamanModel = new PeminjamanModel(connection);
        peminjamanDetailModel = new PeminjamanDetailModel(connection);
    }
    
    private void tableRender(){
        tabelBarangRincian.setModel(peminjamanDetailTableModel);
        tabelBarangRincian.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabelBarangRincian.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelBarangRincian.getColumnModel().getColumn(2).setPreferredWidth(40);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textPeminjamanNomor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textPeminjamanTanggal = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        textNamaPeminjam = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textKodeBuku = new javax.swing.JTextField();
        textNamaBuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textJumlahBuku = new javax.swing.JSpinner();
        buttonBarangSisipkan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelBarangRincian = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buttonPenjualanBaru = new javax.swing.JButton();
        buttonPenjualanSimpan = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("FORMULIR PEMINJAMAN BUKU");

        jLabel1.setText("No. Peminjaman");

        jLabel2.setText("Tanggal");

        textPeminjamanTanggal.setModel(new javax.swing.SpinnerDateModel());
        textPeminjamanTanggal.setEditor(new javax.swing.JSpinner.DateEditor(textPeminjamanTanggal, "dd/MM/yyyy"));

        jLabel12.setText("Nama Peminjam");

        textNamaPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaPeminjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPeminjamanNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPeminjamanTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPeminjamanNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(textPeminjamanTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addComponent(textNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku yang dipinjam"));

        jLabel3.setText("Kode Buku");

        jLabel5.setText("Jumlah");

        textJumlahBuku.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        textJumlahBuku.setEditor(new javax.swing.JSpinner.NumberEditor(textJumlahBuku, "#,##0"));
        textJumlahBuku.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                textJumlahBukuStateChanged(evt);
            }
        });

        buttonBarangSisipkan.setText("SISIPKAN");
        buttonBarangSisipkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarangSisipkanActionPerformed(evt);
            }
        });

        jLabel11.setText("Nama Buku");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBarangSisipkan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNamaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textJumlahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBarangSisipkan))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 47, Short.MAX_VALUE))))
        );

        jLabel8.setText("Rincian Buku yang dipinjam");

        tabelBarangRincian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tabelBarangRincian);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonPenjualanBaru.setText("BARU");
        buttonPenjualanBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenjualanBaruActionPerformed(evt);
            }
        });

        buttonPenjualanSimpan.setText("SIMPAN");
        buttonPenjualanSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenjualanSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(688, Short.MAX_VALUE)
                .addComponent(buttonPenjualanBaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPenjualanSimpan)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPenjualanBaru)
                    .addComponent(buttonPenjualanSimpan))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 709, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textJumlahBukuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_textJumlahBukuStateChanged
        
    }//GEN-LAST:event_textJumlahBukuStateChanged

    private void buttonBarangSisipkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarangSisipkanActionPerformed
        if (textKodeBuku.getText().isEmpty() || textNamaBuku.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "HARAP ISI FORM", "PERINGATAN", JOptionPane.INFORMATION_MESSAGE);
            return; 
        }
        PeminjamanDetail peminjamanDetail = new PeminjamanDetail();
        peminjamanDetail.setKode_buku(textKodeBuku.getText());
        peminjamanDetail.setNama_buku(textNamaBuku.getText());
        peminjamanDetail.setJumlah(Integer.valueOf(String.valueOf(textJumlahBuku.getValue())));
        boolean add = true;
        for(PeminjamanDetail peminjamanDetailOld : peminjamanDetailTableModel.getRows()){
            if (peminjamanDetailOld.getPeminjaman() != null &&
                peminjamanDetail.getPeminjaman() != null &&
                peminjamanDetailOld.getPeminjaman().getPeminjam().equals(peminjamanDetail.getPeminjaman().getPeminjam())) {
                add = false;
                break;
            }
        }
        if(add){
            peminjamanDetailTableModel.getRows().add(peminjamanDetail);
            peminjamanDetailTableModel.fireTableDataChanged();
            textKodeBuku.setText(null);
            textNamaBuku.setText(null);
            textJumlahBuku.setValue(1);
        }
    }//GEN-LAST:event_buttonBarangSisipkanActionPerformed

    private void buttonPenjualanBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPenjualanBaruActionPerformed
        textPeminjamanNomor.setText(null);
        textNamaPeminjam.setText(null);
        textKodeBuku.setText(null);
        textNamaBuku.setText(null);
        textJumlahBuku.setValue(1);
        
        peminjamanDetailTableModel.setRows(new ArrayList<PeminjamanDetail>());
        peminjamanDetailTableModel.fireTableDataChanged();
    }//GEN-LAST:event_buttonPenjualanBaruActionPerformed

    private void buttonPenjualanSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPenjualanSimpanActionPerformed
        if (textPeminjamanNomor.getText().isEmpty() || textNamaPeminjam.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "HARAP ISI FORM", "PERINGATAN", JOptionPane.INFORMATION_MESSAGE);
            return; 
        }
        try{
            connection.setAutoCommit(false);
            //insert peminjaman
            Peminjaman peminjaman = new Peminjaman();
            peminjaman.setNo_peminjaman(textPeminjamanNomor.getText());
            peminjaman.setPeminjam(textNamaPeminjam.getText());
            peminjaman.setTanggal((Date)textPeminjamanTanggal.getValue());
            peminjamanModel.insert(peminjaman);
            
            //insert peminjaman detail
            for(PeminjamanDetail detail : peminjamanDetailTableModel.getRows()){
                detail.setPeminjaman(peminjaman);
                peminjamanDetailModel.insert(detail);
            }
            connection.commit();
            JOptionPane.showMessageDialog(this, "DATA TRANSAKSI BERHASIL DISIMPAN", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "DATA TRANSAKSI GAGAL DISIMPAN", "KESALAHAN", JOptionPane.INFORMATION_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buttonPenjualanSimpanActionPerformed

    private void textNamaPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaPeminjamActionPerformed

public static void main(String arg[]){
    try{
        for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
            if("Nimbus".equals(info.getName())){
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    }catch(ClassNotFoundException ex){
        java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(InstantiationException ex){
        java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(IllegalAccessException ex){
        java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }catch(javax.swing.UnsupportedLookAndFeelException ex){
        java.util.logging.Logger.getLogger(PeminjamanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    java.awt.EventQueue.invokeLater(new Runnable(){
       public void run(){
            JFrame frame = new JFrame();
            frame.addWindowListener(new java.awt.event.WindowAdapter(){
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
            });
            PeminjamanForm form = new PeminjamanForm();
            frame.add(form);
            form.setVisible(true);

            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            frame.setVisible(true);
        } 
    });
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBarangSisipkan;
    private javax.swing.JButton buttonPenjualanBaru;
    private javax.swing.JButton buttonPenjualanSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelBarangRincian;
    private javax.swing.JSpinner textJumlahBuku;
    private javax.swing.JTextField textKodeBuku;
    private javax.swing.JTextField textNamaBuku;
    private javax.swing.JTextField textNamaPeminjam;
    private javax.swing.JTextField textPeminjamanNomor;
    private javax.swing.JSpinner textPeminjamanTanggal;
    // End of variables declaration//GEN-END:variables
}


